// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuVAHFL5qxKKX0hM4og_oe4ODdr2vneA',
    appId: '1:233321347526:android:c48268eaaee12528749ac7',
    messagingSenderId: '233321347526',
    projectId: 'amacle-manager-developer-app',
    storageBucket: 'amacle-manager-developer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyLTQBQN5aEdvBpqvEhAOF0SXkKhkLuU',
    appId: '1:233321347526:ios:c0f632df5544f401749ac7',
    messagingSenderId: '233321347526',
    projectId: 'amacle-manager-developer-app',
    storageBucket: 'amacle-manager-developer-app.appspot.com',
    androidClientId: '233321347526-71m9he67um9dli0ft7dotsldue0qvsgp.apps.googleusercontent.com',
    iosClientId: '233321347526-9u5t2t086mu6od9qalbngtg4j3dlolqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.amacleStudioApp',
  );
}
